### ISSUE TITLE
Settings: Missing symbol 'getC'

### ISSUE THREAD

**Issue by only-a-ptr** [cryham/ckeys#1]
Hello, I'm porting cKeys to Rigs of Rods (https://github.com/RigsOfRods/rigs-of-rods/pull/2477) and it appears the `Settings::getC` function as well as static vars in `Settings` are not defined, so the app shouldn't even build.

I didn't try to build ckeys alone though, I discovered this during my work. Sorry if I missed something.

**Comment by cryham** [comment]
Hi. You are right. Those were missing. I don't remember how that happened. I lost my old sources so I wrote it again.
Should be working now.
